py.install_sources(
  [
    '__init__.py',
    '__init__.pxd',
    'acb.pxd',
    'acb_calc.pxd',
    'acb_dft.pxd',
    'acb_dirichlet.pxd',
    'acb_elliptic.pxd',
    'acb_hypgeom.pxd',
    'acb_mat.pxd',
    'acb_modular.pxd',
    'acb_poly.pxd',
    'acb_theta.pxd',
    'arb.pxd',
    'arb_fmpz_poly.pxd',
    'arb_hypgeom.pxd',
    'arb_mat.pxd',
    'arb_poly.pxd',
    'arf.pxd',
    'arith.pxd',
    'bernoulli.pxd',
    'compat.pxd',
    'dirichlet.pxd',
    'flint.pxd',
    'fmpq.pxd',
    'fmpq_mat.pxd',
    'fmpq_mpoly.pxd',
    'fmpq_mpoly_factor.pxd',
    'fmpq_poly.pxd',
    'fmpq_vec.pxd',
    'fmpz.pxd',
    'fmpz_factor.pxd',
    'fmpz_lll.pxd',
    'fmpz_mat.pxd',
    'fmpz_mod.pxd',
    'fmpz_mod_mat.pxd',
    'fmpz_mod_mpoly.pxd',
    'fmpz_mod_mpoly_factor.pxd',
    'fmpz_mod_poly.pxd',
    'fmpz_mod_poly_factor.pxd',
    'fmpz_mod_vec.pxd',
    'fmpz_mpoly.pxd',
    'fmpz_mpoly_factor.pxd',
    'fmpz_mpoly_q.pxd',
    'fmpz_poly.pxd',
    'fmpz_poly_factor.pxd',
    'fmpz_vec.pxd',
    'fq.pxd',
    'fq_default.pxd',
    'fq_default_mat.pxd',
    'fq_default_poly.pxd',
    'fq_default_poly_factor.pxd',
    'fq_mat.pxd',
    'fq_nmod.pxd',
    'fq_nmod_mat.pxd',
    'fq_nmod_poly.pxd',
    'fq_nmod_poly_factor.pxd',
    'fq_poly.pxd',
    'fq_poly_factor.pxd',
    'fq_zech.pxd',
    'fq_zech_mat.pxd',
    'fq_zech_poly.pxd',
    'fq_zech_poly_factor.pxd',
    'gr.pxd',
    'gr_domains.pxd',
    'gr_generic.pxd',
    'gr_implementing.pxd',
    'gr_mat.pxd',
    'gr_mpoly.pxd',
    'gr_poly.pxd',
    'gr_special.pxd',
    'gr_vec.pxd',
    'mag.pxd',
    'mpoly.pxd',
    'nmod.pxd',
    'nmod_mat.pxd',
    'nmod_mpoly.pxd',
    'nmod_mpoly_factor.pxd',
    'nmod_poly.pxd',
    'nmod_poly_factor.pxd',
    'nmod_vec.pxd',
    'partitions.pxd',
    'ulong_extras.pxd',
  ],
  pure: false,
  subdir: 'flint/flintlib/functions',
)
