py.install_sources(
  [
    '__init__.py',
    'acb.pxd',
    'acb_calc.pxd',
    'acb_dirichlet.pxd',
    'acb_theta.pxd',
    'arb.pxd',
    'arf.pxd',
    'arith.pxd',
    'dirichlet.pxd',
    'flint.pxd',
    'fmpq.pxd',
    'fmpz.pxd',
    'fmpz_mod.pxd',
    'fmpz_mod_mat_compat.pxd',
    'fmpz_mod_poly.pxd',
    'fq.pxd',
    'fq_default.pxd',
    'fq_nmod.pxd',
    'fq_zech.pxd',
    'gr.pxd',
    'mpoly.pxd',
    'nmod.pxd',
    'undocumented.pxd',
  ],
  pure: false,
  subdir: 'flint/flintlib/types',
)
