from typing import overload

from ..flint_base.flint_base import flint_scalar
from .fmpz import fmpz
from .fmpq import fmpq


_str = str
ifmpz = int | fmpz
ifmpq = int | fmpz | fmpq
iarf_cmp = int | float | fmpz | fmpq | arf
iarf_arith = int | float | fmpz | arf


class arf(flint_scalar):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg: iarf_cmp | tuple[ifmpz, ifmpz] | _str, /) -> None: ...

    def is_finite(self) -> bool: ...
    def is_pos_inf(self) -> bool: ...
    def is_neg_inf(self) -> bool: ...
    def is_nan(self) -> bool: ...
    def is_zero(self) -> bool: ...

    def man_exp(self) -> tuple[fmpz, fmpz]: ...

    def _repr_str(self) -> _str: ...
    def _dec_str(self, num_digits: int | None = None) -> _str: ...

    def __str__(self) -> _str: ...
    def __repr__(self) -> _str: ...

    def __bool__(self) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...

    def as_integer_ratio(self) -> tuple[int, int]: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __lt__(self, other: iarf_cmp, /) -> bool: ...
    def __le__(self, other: iarf_cmp, /) -> bool: ...
    def __gt__(self, other: iarf_cmp, /) -> bool: ...
    def __ge__(self, other: iarf_cmp, /) -> bool: ...

    def __neg__(self) -> arf: ...
    def __pos__(self) -> arf: ...
    def __abs__(self) -> arf: ...

    def __add__(self, other: iarf_arith, /) -> arf: ...
    def __radd__(self, other: iarf_arith, /) -> arf: ...
    def __sub__(self, other: iarf_arith, /) -> arf: ...
    def __rsub__(self, other: iarf_arith, /) -> arf: ...
    def __mul__(self, other: iarf_arith, /) -> arf: ...
    def __rmul__(self, other: iarf_arith, /) -> arf: ...
    def __truediv__(self, other: iarf_arith, /) -> arf: ...
    def __rtruediv__(self, other: iarf_arith, /) -> arf: ...
