from __future__ import annotations

from flint.types.acb import acb
from flint.types.fmpz import fmpz


class dirichlet_group:
    def __init__(self, q: int, /) -> None: ...
    def size(self) -> int: ...
    @property
    def q(self) -> fmpz: ...
    def exponent(self) -> fmpz: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


class dirichlet_char:
    def __init__(self, q: int, l: int = 1, /) -> None: ...
    def group(self) -> dirichlet_group: ...
    def index(self) -> int: ...
    def modulus(self) -> fmpz: ...
    def number(self) -> int: ...
    def order(self) -> int: ...
    def is_real(self) -> bool: ...
    def is_primitive(self) -> bool: ...
    def conductor(self) -> int: ...
    def is_principal(self) -> bool: ...
    def parity(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __mul__(self, other: dirichlet_char, /) -> dirichlet_char: ...
    def __call__(self, n: int | fmpz, /) -> acb: ...
    def chi_exponent(self, n: int | fmpz, /) -> fmpz | None: ...
    def l_function(self, s: int | float | complex | str | acb | fmpz, /) -> acb: ...
    def l(self, s: int | float | complex | str | acb | fmpz, /) -> acb: ...
    def hardy_z(self, s: int | float | complex | str | acb | fmpz, /) -> acb: ...
