from __future__ import annotations

from collections.abc import Iterator, Sequence

from .fmpq import fmpq, ifmpq

_str = str


class fmpq_vec:
    def __init__(self, iterable_or_len: Sequence[ifmpq] | int, double_indirect: bool = False) -> None: ...

    def __getitem__(self, x: int, /) -> fmpq: ...
    def __setitem__(self, x: int, y: ifmpq, /) -> None: ...

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[fmpq]: ...

    def str(self, *args: object) -> _str: ...
    def repr(self, *args: object) -> _str: ...

    def __str__(self) -> _str: ...
    def __repr__(self) -> _str: ...
