from __future__ import annotations

from collections.abc import Iterable, Iterator, Sequence
from typing import Literal, overload

from flint.flint_base.flint_base import flint_mat
from flint.types.fmpq import fmpq, ifmpq
from flint.types.fmpq_poly import fmpq_poly
from flint.types.fmpz import fmpz
from flint.types.fmpz_mat import fmpz_mat

_str = str

ifmpq_mat = fmpq_mat | fmpz_mat | Sequence[Sequence[ifmpq]]


class fmpq_mat(flint_mat[fmpq]):
    @overload
    def __init__(self, val: ifmpq_mat, /) -> None: ...
    @overload
    def __init__(self, m: int, n: int, /) -> None: ...
    @overload
    def __init__(self, m: int, n: int, entries: Iterable[ifmpq], /) -> None: ...

    def __bool__(self) -> bool: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

    def __getitem__(self, index: tuple[int, int], /) -> fmpq: ...
    def __setitem__(self, index: tuple[int, int], value: ifmpq, /) -> None: ...
    def __iter__(self) -> Iterator[fmpq]: ...
    def entries(self) -> list[fmpq]: ...
    def table(self) -> list[list[fmpq]]: ...
    def tolist(self) -> list[list[fmpq]]: ...

    def det(self) -> fmpq: ...
    def __pos__(self) -> fmpq_mat: ...
    def __neg__(self) -> fmpq_mat: ...
    def __add__(self, other: fmpq_mat | fmpz_mat, /) -> fmpq_mat: ...
    def __sub__(self, other: fmpq_mat | fmpz_mat, /) -> fmpq_mat: ...
    def __mul__(self, other: fmpq_mat | fmpz_mat | ifmpq, /) -> fmpq_mat: ...
    def __rmul__(self, other: fmpz_mat | ifmpq, /) -> fmpq_mat: ...
    def __truediv__(self, other: ifmpq, /) -> fmpq_mat: ...

    def inv(self) -> fmpq_mat: ...
    def transpose(self) -> fmpq_mat: ...
    def solve(
        self,
        other: fmpq_mat | fmpz_mat,
        algorithm: Literal["fflu", "dixon"] | None = None,
        /,
    ) -> fmpq_mat: ...
    def rref(self, inplace: bool = False, /) -> tuple[fmpq_mat, int]: ...
    def rank(self) -> int: ...
    @classmethod
    def hilbert(cls, n: int, m: int, /) -> fmpq_mat: ...
    def numer_denom(self) -> tuple[fmpz_mat, fmpz]: ...
    def charpoly(self) -> fmpq_poly: ...
    def minpoly(self) -> fmpq_poly: ...
    def __pow__(self, exponent: int, modulo: None = None, /) -> fmpq_mat: ...

    def str(self, *args: object, **kwargs: object) -> _str: ...
    def repr(self) -> _str: ...
    def __str__(self) -> _str: ...
    def __repr__(self) -> _str: ...
