from __future__ import annotations

from collections.abc import Iterator, Sequence

from .fmpz import fmpz, ifmpz

_str = str


class fmpz_vec:
    def __init__(self, iterable_or_len: Sequence[ifmpz] | int, double_indirect: bool = False) -> None: ...

    def __getitem__(self, x: int, /) -> fmpz: ...
    def __setitem__(self, x: int, y: ifmpz, /) -> None: ...

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[fmpz]: ...

    def str(self, *args: object) -> _str: ...
    def repr(self, *args: object) -> _str: ...

    def __str__(self) -> _str: ...
    def __repr__(self) -> _str: ...
