from __future__ import annotations

from collections.abc import Sequence
from typing import overload

from flint.flint_base.flint_base import flint_mat
from flint.types.fmpz import fmpz
from flint.types.fmpz_mat import fmpz_mat
from flint.types.fmpz_mod import fmpz_mod, fmpz_mod_ctx, ifmpz_mod
from flint.types.fmpz_mod_poly import fmpz_mod_poly
from flint.types.nmod_mat import nmod_mat

class fmpz_mod_mat(flint_mat[fmpz_mod]):
    @overload
    def __init__(self, m: int, n: int, entries: Sequence[ifmpz_mod], ctx: fmpz_mod_ctx, /) -> None: ...
    @overload
    def __init__(self, m: int, n: int, ctx: fmpz_mod_ctx, /) -> None: ...
    @overload
    def __init__(self, val: Sequence[Sequence[ifmpz_mod]], ctx: fmpz_mod_ctx, /) -> None: ...
    @overload
    def __init__(self, val: fmpz_mod_mat | fmpz_mat | nmod_mat, ctx: fmpz_mod_ctx, /) -> None: ...
    @overload
    def __init__(self, val: fmpz_mod_mat | nmod_mat, /) -> None: ...

    def nrows(self) -> int: ...
    def ncols(self) -> int: ...
    def modulus(self) -> fmpz: ...
    def repr(self) -> str: ...
    def entries(self) -> list[fmpz_mod]: ...
    def __getitem__(self, index: tuple[int, int], /) -> fmpz_mod: ...
    def __setitem__(self, index: tuple[int, int], value: ifmpz_mod, /) -> None: ...

    def __bool__(self) -> bool: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __pos__(self) -> fmpz_mod_mat: ...
    def __neg__(self) -> fmpz_mod_mat: ...

    def __add__(self, other: fmpz_mod_mat | fmpz_mat | nmod_mat, /) -> fmpz_mod_mat: ...
    def __radd__(self, other: fmpz_mod_mat | fmpz_mat | nmod_mat, /) -> fmpz_mod_mat: ...
    def __sub__(self, other: fmpz_mod_mat | fmpz_mat | nmod_mat, /) -> fmpz_mod_mat: ...
    def __rsub__(self, other: fmpz_mod_mat | fmpz_mat | nmod_mat, /) -> fmpz_mod_mat: ...
    def __mul__(self, other: fmpz_mod_mat | fmpz_mat | nmod_mat | ifmpz_mod, /) -> fmpz_mod_mat: ...
    def __rmul__(self, other: fmpz_mod_mat | fmpz_mat | nmod_mat | ifmpz_mod, /) -> fmpz_mod_mat: ...
    def __pow__(self, other: int, /) -> fmpz_mod_mat: ...
    def __truediv__(self, other: ifmpz_mod, /) -> fmpz_mod_mat: ...

    def inv(self) -> fmpz_mod_mat: ...
    def det(self) -> fmpz_mod: ...
    def charpoly(self) -> fmpz_mod_poly: ...
    def minpoly(self) -> fmpz_mod_poly: ...
    def transpose(self) -> fmpz_mod_mat: ...
    def solve(self, rhs: fmpz_mod_mat | nmod_mat, /) -> fmpz_mod_mat: ...
    def rank(self) -> int: ...
    def rref(self, inplace: bool = False, /) -> tuple[fmpz_mod_mat, int]: ...
