from __future__ import annotations

from typing import Callable, ParamSpec, TypeVar


_P = ParamSpec("_P")
_R = TypeVar("_R")


class FlintContext:
    pretty: bool
    unicode: bool

    def __init__(self) -> None: ...
    def default(self) -> None: ...

    @property
    def prec(self) -> int: ...
    @prec.setter
    def prec(self, prec: int) -> None: ...

    @property
    def dps(self) -> int: ...
    @dps.setter
    def dps(self, prec: int) -> None: ...

    @property
    def cap(self) -> int: ...
    @cap.setter
    def cap(self, cap: int) -> None: ...

    @property
    def threads(self) -> int: ...
    @threads.setter
    def threads(self, num: int) -> None: ...

    def extraprec(self, n: int) -> PrecisionManager: ...
    def extradps(self, n: int) -> PrecisionManager: ...
    def workprec(self, n: int) -> PrecisionManager: ...
    def workdps(self, n: int) -> PrecisionManager: ...

    def __repr__(self) -> str: ...
    def cleanup(self) -> None: ...


class PrecisionManager:
    def __init__(self, ctx: FlintContext, eprec: int = -1, edps: int = -1) -> None: ...
    def __call__(self, func: Callable[_P, _R]) -> Callable[_P, _R]: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: object, value: object, traceback: object) -> None: ...
